timescale: "recent_human"
demography: 
    demo_yaml: "helper_files/demo_params/recent_human.yaml"
    samples_json: "helper_files/demo_params/recent_human_samples.json"
calc_script: "helper_files/calc_scripts/F-statistics-medium_st_admixr_minimal_SMBE.R"
# all of the simulations that we want to run:
parameters: ["pseudohaploid", "deaminate", "ancContam", "mhContam", missing] # "original", , "missing", "ancient_sediment" ""dpFilter", "dpFilterMissing", "
# rates for contamination, deamination, missingness
rates:
    deamination: [0.05, 0.1, 0.25]
    contamination: [0.05, 0.1, 0.25]
    missing: [0.05, 0.1, 0.25]
# population lists for target and modern
pops: 
    target: ["pop2_2", "admix", "pop1_3"] 
    modern: ["mh_contam"] 

selection: ["T", "all"] 

# simulation parameters
ds: ["full", 1000000, ] # 100000, 50000, 30000, 10000, 5000, 2500, 1500, 500, 250
statistics: ["dstat", "f3"] # , "f4", "f3"
chromosomes: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]
tests: ["admix", "relna"] # , "rela"
reps: 5